### ISSUE TITLE
Return Rate needs to be changed to "Price After Hatch"

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#2]
Returns is a scary thing... we are not looking to make any promises of returns... and the returns won't be known until the person sells their tokens.... What we can say is "Price After Hatch" so we should go with that

**Comment by dapplion** [comment]
Fixed with https://github.com/dapplion/augmented-tbc-design/commit/2cc32d5764b238680e7fc88e8c42815d93274ade.

----

![after](https://user-images.githubusercontent.com/35266934/62425077-4dbd8280-b6d7-11e9-835a-7c2e90e049df.png)
