### ISSUE TITLE
Add a vesting period bar

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#4]
and integrate vested token holder behavior to the curve

**Comment by dapplion** [comment]
Zargham suggested adding a price floor as a result of a fraction of the tokens being vested. He developed the equations for it on the [Jupyter notebook in the root of the project](https://github.com/commons-stack/augmented-tbc-design/blob/master/math-translation-for-z.ipynb), and it's already translated to JS and implemented in this commit https://github.com/commons-stack/augmented-tbc-design/commit/9bc519be2db8b7d2c252a61a7b7c374dd5990744

There is also an explanation on the helper text on the meaning of "Price floor"

> **Floor price** | Lower bound of the price guaranteed by the vesting of hatch tokens. It decreases over time as more hatch tokens are allowed to be traded


----

![floor](https://user-images.githubusercontent.com/35266934/62823675-c5862400-bb93-11e9-98ef-248ded406ef1.png)

**Comment by GriffGreen** [comment]
the price floor should never go up... its output 20 on the jupyter notebook

**Comment by GriffGreen** [comment]
The content for the vesting slider:

Vesting Half Life: Tokens that are purchased during the Hatch are locked for 9 weeks and then released slowly such that 50% of the tokens will be able to be sold after this many weeks and 87.5% of the tokens after 3x this many weeks.

(can be improved probably)

**Comment by dapplion** [comment]
> the price floor should never go up... its output 20 on the jupyter notebook

Z found an error on the equation that fucked the floor price values. It's fixed with https://github.com/commons-stack/augmented-tbc-design/commit/655c4ea9d04483e2f2a0f0b28949498bfd0e6925 and now the floor price follows the expected shape.

---

![Screenshot from 2019-08-11 16-00-47](https://user-images.githubusercontent.com/35266934/62834765-37707300-bc51-11e9-85aa-312fa3408ee1.png)

**Comment by dapplion** [comment]
Added a vesting half-life input parameter. It has a direct effect only on the floor price plot.
I copied your description if you want different content to be shown just paste it here and ping me.

---

![vestinggg](https://user-images.githubusercontent.com/35266934/62836499-ec139000-bc63-11e9-965d-51c923f5fb60.png)
