### ISSUE TITLE
Initial raise should be highlighted and after the other curve design parameters

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#5]

**Comment by dapplion** [comment]
Partially resolved, it would be good to bring in a designer's opinion on this issue.

**Comment by GriffGreen** [comment]
Run parameters... wtf does that mean ;-D

I liked this first version:

<img width="598" alt="Screen Shot 2019-08-10 at 9 20 59 PM" src="https://user-images.githubusercontent.com/14945613/62829543-d85d2080-bbb4-11e9-8a0a-82a487faf928.png">

Or even having a bar above the the run simulation that is labeled "Initial Raise" with a giant slider where it's obvious this is the one we want to play with!

**Comment by dapplion** [comment]
I have settled now on this design, open to more ideas or complaints!

---

![inittt](https://user-images.githubusercontent.com/35266934/62836516-1feeb580-bc64-11e9-9afc-48df035c1c43.png)
