### ISSUE TITLE
Explainer edits

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#7]
Hatch % to Funding Pool | The percentage of the funds raised in the Hatch going directly to funding pool to be used to support the Commons, the rest goes to the collateral pool
-- | --
Hatch Price | The price paid per token by when hatching the project
Post-Hatch Price | The price per token after the Hatch ends, the curve is set, and anyone can interact with the bonding curve.
Exit tribute | This is the percentage that goes to the funding pool when token holders "sell"  by burning their token at the price determined by the bonding curve.   
Initial raise | Amount of funds contributed during the hatch period. 

Visualization of the bonding curve up to 4x the initial size of the Collateral Pool Post-Hatch. This result is deterministic given the curve parameters and the initial raise. It will never change regardless of the campaign's performance, it simply shows how the price will react to changes in the Collateral Pool.

**Comment by dapplion** [comment]
Fixed with https://github.com/commons-stack/augmented-tbc-design/commit/e95a33ba1f867c1a659145bced99804c4dbef57c
Thank you for providing the content <3
