### ISSUE TITLE
Explainer Edits Part 2

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#8]
This chart shows a 52 week simulation of discrete transactions interacting with the Augmented Bonding Curve. Each transaction adds to or subtracts reserve from the system, modifying the price over time. The frequency, size and direction of each transaction is computed from a set of bounded random functions. This is a NOT a cadCAD simulation, but it showcases the intention behind cadCAD.

-- | --
Price | Price of the token over time.

Total Funds Raised | Cumulative sum of the funds sent to the Funding Pool.

Collateral Pool Balance | Total DAI in the Collateral Pool at the end of the simulated period
-- | --
Funds generated from initial hatch | Funds raised during the Hatch that go directly to the cause 
Funds generated from exit tributes | Cumulative sum of exit tributes collected from only exit /sell/burn transactions
Average slippage | Average of change in price a user experiences from the current price to the price received for exiting/selling/burning

**Comment by dapplion** [comment]
Fixed with https://github.com/commons-stack/augmented-tbc-design/commit/e95a33ba1f867c1a659145bced99804c4dbef57c
Thank you for providing the content <3
