### ISSUE TITLE
Rename header's title

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#9]
the title and text says "Augmented Token Bonding Curve Design" it should be "Augmented Bonding Curve Design"

**Comment by dapplion** [comment]
@GriffGreen should the subtitle

>  Experiment and test augmented token bonding curves

Be changed also?

**Comment by dapplion** [comment]
Fixed with https://github.com/commons-stack/augmented-tbc-design/commit/e95a33ba1f867c1a659145bced99804c4dbef57c
